# -*- coding: utf-8 -*-
"""mood_tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xo525nB4y4zDhFTuR5pu3rfqs2AwQh1h
"""

# STEP 1: Install required packages (run this once)
!pip install streamlit openpyxl

# STEP 2: Save the Streamlit app code into a Python (.py) file
mood_tracker_code = """
import streamlit as st
import pandas as pd
import datetime
import os

FILE_PATH = 'mood_journal.xlsx'

# Load or create DataFrame
if os.path.exists(FILE_PATH):
    df = pd.read_excel(FILE_PATH)
else:
    df = pd.DataFrame(columns=["Date", "Mood", "Journal"])

# Streamlit UI
st.set_page_config(page_title="Daily Mood Tracker", layout="centered")
st.title("🌞 Daily Mood Tracker with Emoji & Journal")

# Mood options
moods = {
    "😊 Happy": "Happy",
    "😐 Neutral": "Neutral",
    "😔 Sad": "Sad",
    "😤 Stressed": "Stressed",
    "😴 Tired": "Tired",
    "😄 Excited": "Excited",
}

# Select mood
mood_emoji = st.radio("How are you feeling today?", list(moods.keys()))
selected_mood = moods[mood_emoji]

# Journal entry
journal = st.text_area("Write something about your day...")

# Save button
if st.button("Save Entry"):
    new_entry = {
        "Date": datetime.date.today(),
        "Mood": selected_mood,
        "Journal": journal.strip()
    }
    df = pd.concat([df, pd.DataFrame([new_entry])], ignore_index=True)
    df.to_excel(FILE_PATH, index=False)
    st.success("Entry saved successfully!")

# View entries
st.markdown("### 📅 Your Mood History")
if not df.empty:
    st.dataframe(df.sort_values("Date", ascending=False))
else:
    st.info("No entries yet. Start by saving one above!")
"""

# STEP 3: Write the code to a .py file for Streamlit
with open("mood_tracker.py", "w") as f:
    f.write(mood_tracker_code)

print("✅ mood_tracker.py file created! Now you can upload it to Streamlit Cloud.")